### ISSUE TITLE
Allow spawning from redirector (passing on from underlying nodes)

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/tmpnb-redirector#4]
When a user hits the `/api/spawn` endpoint:

```
POST /api/spawn
```

tmpnb redirector would then pass the POST on to one of the tmpnb nodes that has availability, returning their response but with a full path:

```
{'url': 'https://adsfaf.tmpnb.org/user/dsfasdf/'}
```

/cc @captainsafia

**Comment by captainsafia** [comment]
OK, so if I am understanding this right (first time diving into `tmpnb-redirector` codebase), we would like to:

1. Add a `/api/spawn` route to the `tmpnb-redirector` app.
2. Select a node within self.settings.stats that contains the most available containers. 
3. Redirect to that host with the payload originally provided in 1.

Does that seem correct? Also, how do we want to select the "node with availability" in step 2?

**Comment by rgbkrk** [comment]
> Add a /api/spawn route to the tmpnb-redirector app.

Yup!

> Select a node within self.settings.stats that contains the most available containers.

Yup!

> Redirect to that host with the payload originally provided in 1.

Eh... There won't be a payload, the message body will be empty, just like the tmpnb `/api/spawn` endpoint.

> how do we want to select the "node with availability" in step 2?

This currently gets done in the [Reroute Handler](https://github.com/jupyter/tmpnb-redirector/blob/master/redirector.py#L153-L159), randomly selected from the available. You can use that for now, likely adapted into a separate function.

**Comment by captainsafia** [comment]
> Eh... There won't be a payload, the message body will be empty, just like the tmpnb /api/spawn endpoint.

Totally knew that! Was checking to see if you did! ;) But yes, I got it.

> This currently gets done in the Reroute Handler, randomly selected from the available. You can use that for now, likely adapted into a separate function.

Saw that but wasn't sure if we wanted to carry that over. This sounds reasonable and also extension-able.

I think I've got enough here to be able to cook something up! I'll open up a WIP PR and ping you on that if I have any questions.

![giphy 3](https://cloud.githubusercontent.com/assets/1857993/9778137/6d6f5e56-5721-11e5-9f40-80f10ea984c5.gif)

**Comment by captainsafia** [comment]
OK, I'm gonna be absolutely silly and create a bunch of issues for different parts of this right now. For my own sanity. :)

**Comment by rgbkrk** [comment]
> create a bunch of issues for different parts of this right now

Breaking it up is a great way to go. Thank you!

Wow that pink haired hard working cat. :smile_cat:

**Comment by captainsafia** [comment]
I'm waiting for you to realize that I'm actually a cat dressed in a human costume.
